# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Dms2deg
                                 A QGIS plugin
 This plugin converts DMS to degree
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-10-07
        copyright            : (C) 2021 by Ivan Lebedev
        email                : lebedev77@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Ivan Lebedev'
__date__ = '2021-10-07'
__copyright__ = '(C) 2021 by Ivan Lebedev'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Dms2deg class from file Dms2deg.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .dms_2_deg import Dms2degPlugin
    return Dms2degPlugin()
